CREATE TABLE IF NOT EXISTS SCHEDULE  
(
    ID INT PRIMARY KEY NOT NULL,
    GRP VARCHAR(16),
    DAY VARCHAR(16),
    LESSON VARCHAR(256),
    TYPE VARCHAR(32),
    AUDIT VARCHAR(32),
    START_TIME VARCHAR(8),
    END_TIME VARCHAR(8),
    ORD INT,
    EVEN VARCHAR(4),
    WEEK INT[]
);

CREATE TABLE IF NOT EXISTS EXAMS
(
    ID INT PRIMARY KEY NOT NULL,
    GRP VARCHAR(16),
    DAY VARCHAR(16),
    EXAM VARCHAR(256),
    TYPE VARCHAR(64),
    LECTOR VARCHAR (128),
    TIME VARCHAR(16),
    AUDIT VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS profiles
(
    ID SERIAL PRIMARY KEY,
    tgid BIGINT UNIQUE NOT NULL,
    username VARCHAR(64) NOT NULL,
    first_name VARCHAR(64) NOT NULL,
    language_code VARCHAR(8) NOT NULL,
    group_name VARCHAR(64) NOT NULL
);